# Lanes to use in daily development for CI.

default_platform(:ios)

platform :ios do
    # uses `versioning` plugin
  desc "Update application build number with ci build number"
  lane :set_build_number_from_ci do
    increment_build_number_in_plist(
      build_number: ci_build_number
    )
  end

  desc "Increment application patch version number (#.#.x -> #.#.x+1)"
  lane :increment_version_number_patch do
    increment_version_number_in_plist
  end
end
